// Generated by CoffeeScript 2.7.0
(function() {
  // Requerir los módulos necesarios
  var fs, html, pug;

  pug = require('pug');

  fs = require('fs');

  // Compilar el archivo Pug a HTML
  html = pug.renderFile('./debug/index.pug');

  // Escribir el resultado en un archivo HTML
  fs.writeFileSync('index.html', html);

  console.log('Archivo HTML generado con éxito.');

}).call(this);
